name: Run the unit tests
on: 
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - uses: ./.github/actions/install-dependencies
          
      - name: Run pytest
        run: pytest

  runmigrations:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4
      
        - uses: ./.github/actions/install-dependencies
      
        - name: Run django migrate
          run: python manage.py migrate

  migrations-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - uses: ./.github/actions/install-dependencies
          
      - name: Run pytest
        run: pytest
      
      - name: Run django migrate
        run: python manage.py makemigrations --check
