# name: Hello Github Actions
# on: [push]
# jobs:
#   examples:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Test
#         run: |
#           echo "Hello World"

#       - name: Test 2
#         run: |
#           echo "GoodBye World"

      # - name: Install dependencies
      #   run: |
      #     python -m pip install -upgrade pip
      #     pip install -r requirements.txt
          
      # - name: Run pytest
      #   run: pytest